<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>StardewGallery</RootNamespace>
    <AssemblyName>StardewGallery</AssemblyName>
    <Version>2.9.0</Version>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableModDeploy>false</EnableModDeploy>
    <EnableModZip>true</EnableModZip>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.1" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(GamePath)\smapi-internal\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(GamePath)\smapi-internal\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="diagnostics\**\*.cs" />
    <None Remove="diagnostics\**\*" />
    <Compile Remove="SourcesRuntimeChecks\**\*.cs" />
    <None Remove="SourcesRuntimeChecks\**\*" />
    <Compile Remove="Checks\**\*.cs" />
    <None Remove="Checks\**\*" />
    <Compile Remove="PersistenceChecks\**\*.cs" />
    <None Remove="PersistenceChecks\**\*" />
    <None Remove="event-photos\**\*" />
    <None Remove="user-data\**\*" />
    <None Remove="ai-mod-exclusion.json" />
    <None Remove="exclusion-cache\**\*" />
  </ItemGroup>
</Project>
