<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>StardewGallery</RootNamespace>
    <AssemblyName>StardewGallery</AssemblyName>
    <Version>1.0.0</Version>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableModDeploy>false</EnableModDeploy>
    <EnableModZip>true</EnableModZip>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.1" />
    <Reference Include="0Harmony">
      <HintPath>$(GamePath)\smapi-internal\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Checks\**\*.cs" />
    <None Remove="Checks\**\*" />
  </ItemGroup>
</Project>
